# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    nodejs: "22"

  jobs:

    # Build JupyterLite assets
    pre_build:
      - pip install uv
      - uv python install
      - uv sync --locked --all-extras --dev --directory=demo
      - mkdir -p demo/contents
      - cp demo/README.md demo/contents/
      - uv run --directory=demo jupyter lite build --output-dir=

    # Build documentation
    build:
      html:
        - pip install jupyter-book
        - npm run docs:build

        # Copy documentation output
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - cp -r _build/html/* $READTHEDOCS_OUTPUT/html/
        - rm -rf _build

        # Copy JupyterLite into docs
        - mv demo/dist $READTHEDOCS_OUTPUT/html/lite
