# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    nodejs: "22"

  jobs:

    # Build JupyterLite assets
    pre_build:
      - pip install uv
      - cd demo
      - pwd
      - ls -la
      - ls -la uv.lock
      - uv python install
      - uv sync --locked --all-extras --dev
      - mkdir -p contents
      - cp README.md contents/
      - uv run jupyter lite build
      - cd ..

    # Build documentation
    build:
      - pip install jupyter-book
      - npm install
      - npm run docs:build

      # Copy documentation output
      - mkdir -p $READTHEDOCS_OUTPUT/html
      - cp -r _build/html/* $READTHEDOCS_OUTPUT/html/

      # Copy JupyterLite into docs
      - mv demo/dist $READTHEDOCS_OUTPUT/html/lite
