[build-system]
requires = ["hatchling>=1.5.0"]
build-backend = "hatchling.build"

[project]
name = "jupyterlite_ai"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
description = "A serverless AI code completions and chat (meta-package)"
authors = [
    { name = "Jupyter Development Team", email = "jupyter@googlegroups.com" },
]
keywords = ["jupyter", "jupyterlab", "jupyterlite", "jupyterlab-extension"]
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]
dependencies = [
    "jupyternaut-persona ==0.20.1",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://jupyterlite-ai.readthedocs.io/en/latest/"
Repository = "https://github.com/jupyterlite/ai"
Changelog = "https://jupyterlite-ai.readthedocs.io/en/latest/changelog/"
Source = "https://github.com/jupyterlite/ai/tree/main"
Issues = "https://github.com/jupyterlite/ai/issues/new/choose"
"Try it" = "https://jupyterlite.github.io/ai/lab/index.html"

[project.optional-dependencies]
jupyter = [
    "jupyterlab>=4.5.0",
    "jupyterlite>=0.8.0",
    "notebook>=7.5.0"
]
docs = [
    "jupyter-book",
]

[tool.hatch.version]
path = "jupyterlite_ai/_version.py"
