/**
 * This file is generated by `jlpm sync:model-info`.
 * Source: https://models.dev/api.json
 * Backed by: https://github.com/anomalyco/models.dev
 * Generated: 2026-04-28T11:55:05.327Z
 */

import type { IProviderModelInfo } from '../tokens';

export const BUILT_IN_PROVIDER_MODEL_INFO: Record<
  string,
  Record<string, IProviderModelInfo>
> = {
  anthropic: {
    'claude-opus-4-6': {
      contextWindow: 1000000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-sonnet-4-6': {
      contextWindow: 1000000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-opus-4-5': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-opus-4-5-20251101': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-sonnet-4-5': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-sonnet-4-5-20250929': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-haiku-4-5': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-haiku-4-5-20251001': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-opus-4-1': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-opus-4-1-20250805': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-opus-4-0': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-opus-4-20250514': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-sonnet-4-0': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'claude-sonnet-4-20250514': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    }
  },
  google: {
    'gemini-3.1-pro-preview': {
      contextWindow: 1048576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: true
    },
    'gemini-3.1-pro-preview-customtools': {
      contextWindow: 1048576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: true
    },
    'gemini-3.1-flash-image-preview': {
      contextWindow: 131072,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gemini-3.1-flash-lite-preview': {
      contextWindow: 1048576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: true
    },
    'gemini-3-flash-preview': {
      contextWindow: 1048576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: true
    },
    'gemini-2.5-pro': {
      contextWindow: 1048576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: true
    },
    'gemini-2.5-flash': {
      contextWindow: 1048576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: true
    },
    'gemini-2.5-flash-image': {
      contextWindow: 32768,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gemini-2.5-flash-lite': {
      contextWindow: 1048576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: true
    },
    'gemini-flash-latest': {
      contextWindow: 1048576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: true
    },
    'gemini-flash-lite-latest': {
      contextWindow: 1048576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: true
    }
  },
  mistral: {
    'mistral-large-latest': {
      contextWindow: 262144,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'mistral-medium-latest': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'mistral-medium-2508': {
      contextWindow: 262144,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'mistral-small-latest': {
      contextWindow: 256000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'mistral-small-2506': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'ministral-3b-latest': {
      contextWindow: 128000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    'ministral-8b-latest': {
      contextWindow: 128000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    'magistral-small-latest': {
      contextWindow: 128000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    'magistral-small': {
      contextWindow: 128000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    'magistral-medium-latest': {
      contextWindow: 128000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    'pixtral-large-latest': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'codestral-latest': {
      contextWindow: 256000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    'devstral-latest': {
      contextWindow: 128000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    'devstral-small-2507': {
      contextWindow: 128000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    }
  },
  openai: {
    'gpt-5.4': {
      contextWindow: 1050000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-5.4-mini': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5.4-nano': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5.2': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5.2-2025-12-11': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5.2-chat-latest': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5.2-pro': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5.2-pro-2025-12-11': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5.2-codex': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-5.1': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5.1-2025-11-13': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5.1-chat-latest': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5-2025-08-07': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5-chat-latest': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5-mini': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5-mini-2025-08-07': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5-nano': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-5-nano-2025-08-07': {
      contextWindow: 400000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'o4-mini': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'o4-mini-2025-04-16': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'o3-pro': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    o3: {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'o3-2025-04-16': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'o3-mini': {
      contextWindow: 200000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    'o3-mini-2025-01-31': {
      contextWindow: 200000,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    o1: {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'o1-2024-12-17': {
      contextWindow: 200000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-4.1': {
      contextWindow: 1047576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-4.1-2025-04-14': {
      contextWindow: 1047576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-4.1-mini': {
      contextWindow: 1047576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-4.1-mini-2025-04-14': {
      contextWindow: 1047576,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-4.1-nano': {
      contextWindow: 1047576,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-4.1-nano-2025-04-14': {
      contextWindow: 1047576,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-4o': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-4o-2024-05-13': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-4o-2024-08-06': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-4o-2024-11-20': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-4o-mini': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-4o-mini-2024-07-18': {
      contextWindow: 128000,
      supportsImages: true,
      supportsPdf: true,
      supportsAudio: false
    },
    'gpt-3.5-turbo': {
      contextWindow: 16385,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    },
    'gpt-3.5-turbo-0125': {
      contextWindow: 16385,
      supportsImages: false,
      supportsPdf: false,
      supportsAudio: false
    }
  }
};
